name: Publish win-x64-aot

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.100'

      - name: Build and publish with AOT compilation
        run: |
          dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=true -maxcpucount:1

      - name: Create release
        uses: softprops/action-gh-release@v2.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Dev release 0.1.${{ github.run_number }}
          tag_name: v0.1.${{ github.run_number }}-dev
          files: ${{ github.workspace }}/.out/bin/native/Scranton.exe
          draft: false
          prerelease: false